FROM python:3
RUN echo git clone https://github.com/pythonincontainers/buildtime-runtime >> /tmp/extreme.sh
RUN echo cd buildtime-runtime >> /tmp/extreme.sh
RUN echo bash run-server.sh >> /tmp/extreme.sh
CMD ["/bin/bash", "/tmp/extreme.sh"]
