FROM python:3.7.3
WORKDIR /django-mysite
COPY . .
ARG DJANGO_VER=2.2.1
RUN pip install -r requirements.txt
RUN mkdir -p /data && python manage.py migrate
RUN bash create-admin.sh
VOLUME /data
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
